package demo.repository;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import demo.domainModel.ModelUser;
import demo.domainModel.ModelUserExample;

@Repository
@Mapper
public interface RepositoryUser {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table plusyearmonthday
	 * @mbg.generated  Thu May 21 13:01:10 JST 2020
	 */
	long countByExample(ModelUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table plusyearmonthday
	 * @mbg.generated  Thu May 21 13:01:10 JST 2020
	 */
	int deleteByExample(ModelUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table plusyearmonthday
	 * @mbg.generated  Thu May 21 13:01:10 JST 2020
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table plusyearmonthday
	 * @mbg.generated  Thu May 21 13:01:10 JST 2020
	 */
	int insert(ModelUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table plusyearmonthday
	 * @mbg.generated  Thu May 21 13:01:10 JST 2020
	 */
	int insertSelective(ModelUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table plusyearmonthday
	 * @mbg.generated  Thu May 21 13:01:10 JST 2020
	 */
	List<ModelUser> selectByExample(ModelUserExample example);

	List<ModelUser> selectByExample();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table plusyearmonthday
	 * @mbg.generated  Thu May 21 13:01:10 JST 2020
	 */
	ModelUser selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table plusyearmonthday
	 * @mbg.generated  Thu May 21 13:01:10 JST 2020
	 */
	int updateByExampleSelective(@Param("record") ModelUser record, @Param("example") ModelUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table plusyearmonthday
	 * @mbg.generated  Thu May 21 13:01:10 JST 2020
	 */
	int updateByExample(@Param("record") ModelUser record, @Param("example") ModelUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table plusyearmonthday
	 * @mbg.generated  Thu May 21 13:01:10 JST 2020
	 */
	int updateByPrimaryKeySelective(ModelUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table plusyearmonthday
	 * @mbg.generated  Thu May 21 13:01:10 JST 2020
	 */
	int updateByPrimaryKey(ModelUser record);
}