package demo.domainModel;

import lombok.Data;

@Data
public class ModelUser {/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column plusyearmonthday.ID
	 * @mbg.generated  Thu May 21 13:01:10 JST 2020
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column plusyearmonthday.NAME
	 * @mbg.generated  Thu May 21 13:01:10 JST 2020
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column plusyearmonthday.YEAR
	 * @mbg.generated  Thu May 21 13:01:10 JST 2020
	 */
	private Integer year;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column plusyearmonthday.MONTH
	 * @mbg.generated  Thu May 21 13:01:10 JST 2020
	 */
	private Integer month;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column plusyearmonthday.DAY
	 * @mbg.generated  Thu May 21 13:01:10 JST 2020
	 */
	private Integer day;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column plusyearmonthday.ID
	 * @return  the value of plusyearmonthday.ID
	 * @mbg.generated  Thu May 21 13:01:10 JST 2020
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column plusyearmonthday.ID
	 * @param id  the value for plusyearmonthday.ID
	 * @mbg.generated  Thu May 21 13:01:10 JST 2020
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column plusyearmonthday.NAME
	 * @return  the value of plusyearmonthday.NAME
	 * @mbg.generated  Thu May 21 13:01:10 JST 2020
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column plusyearmonthday.NAME
	 * @param name  the value for plusyearmonthday.NAME
	 * @mbg.generated  Thu May 21 13:01:10 JST 2020
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column plusyearmonthday.YEAR
	 * @return  the value of plusyearmonthday.YEAR
	 * @mbg.generated  Thu May 21 13:01:10 JST 2020
	 */
	public Integer getYear() {
		return year;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column plusyearmonthday.YEAR
	 * @param year  the value for plusyearmonthday.YEAR
	 * @mbg.generated  Thu May 21 13:01:10 JST 2020
	 */
	public void setYear(Integer year) {
		this.year = year;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column plusyearmonthday.MONTH
	 * @return  the value of plusyearmonthday.MONTH
	 * @mbg.generated  Thu May 21 13:01:10 JST 2020
	 */
	public Integer getMonth() {
		return month;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column plusyearmonthday.MONTH
	 * @param month  the value for plusyearmonthday.MONTH
	 * @mbg.generated  Thu May 21 13:01:10 JST 2020
	 */
	public void setMonth(Integer month) {
		this.month = month;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column plusyearmonthday.DAY
	 * @return  the value of plusyearmonthday.DAY
	 * @mbg.generated  Thu May 21 13:01:10 JST 2020
	 */
	public Integer getDay() {
		return day;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column plusyearmonthday.DAY
	 * @param day  the value for plusyearmonthday.DAY
	 * @mbg.generated  Thu May 21 13:01:10 JST 2020
	 */
	public void setDay(Integer day) {
		this.day = day;
	}
}